### ISSUE TITLE
Request to add additional environment variables to the KubernetesDriver in the component-orchestrator

### ISSUE THREAD

**Issue by cggrafana12** [openintegrationhub/openintegrationhub.github.io#67]
When i try to share large data using flow getting  below error in step1.
Error: Outgoing message size 23419488 exceeds limit of 10485760.
    at Amqp.prepareMessageAndSendToExchange (/usr/src/app/node_modules/@openintegrationhub/ferryman/lib/amqp.js:365:27)
    at Amqp.sendBackChannel (/usr/src/app/node_modules/@openintegrationhub/ferryman/lib/amqp.js:393:21)
    at TaskExec.onData (/usr/src/app/node_modules/@openintegrationhub/ferryman/lib/ferryman.js:1018:54)
    at TaskExec.emit (/usr/src/app/node_modules/@openintegrationhub/ferryman/lib/emitter.js:182:23)
    at TaskExec.sftpProcess (/usr/src/app/lib/actions/sftp.js:38:18)
    at async TaskExec.process (/usr/src/app/node_modules/@openintegrationhub/ferryman/lib/executor.js:39:26)
    
When i rise this issue in Slack channel i got a response from team. as per the response i checked manually increase OUTGOING message limit it's working fine but when i restart the Flow  it didn't worked. as per theire suggestion i raised PR for this incident. 
 And  i  have seen another issue where as 
After increasing  message limit to component(in secret) then  i'm able to send the 20mb  data. when i retried 100MB i faced out of heap memory  issues like below.

**[1:0x7f6ffa5a54c0]    40309 ms: Scavenge 333.9 (367.1) -> 333.9 (367.6) MB, 66.68 / 0.00 ms  (average mu = 0.788, current mu = 0.872) allocation failure;
[1:0x7f6ffa5a54c0]    41401 ms: Mark-Compact 717.9 (751.7) -> 596.3 (638.0) MB, 525.42 / 0.03 ms  (+ 0.1 ms in 2 steps since start of marking, biggest step 0.1 ms, walltime since start of marking 2573 ms) (average mu = 0.926, current mu = 0.930) finalize
<--- JS stacktrace --->
FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory** 
****
i tried adding
- name: NODE_OPTIONS
value: --max-old-space-size=4096
manually in component deployment but it didn't change.

please help me to resolve his issue. Thanks in advance.

**Comment by RobinBrinkmann** [comment]
This is not an documentation issue. As mentioned, it is also being discussed on slack. I will close it here. Please feel free to contribute a solution to the main repo via PR.
