### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by cggrafana12** [openintegrationhub/openintegrationhub.github.io#68]
when i start the flow i got like below
{"name":"component-orchestrator","hostname":"component-orchestrator-5bdd8c6675-zqwsn","pid":18,"service":"ComponentOrchestrator","flowId":"64b16b90664a0362e0d886d2","level":50,"err":{"message":"403 - {\"message\":\"FORBIDDEN\"}","name":"StatusCodeError","stack":"StatusCodeError: 403 - {\"message\":\"FORBIDDEN\"}\n    at new StatusCodeError (/usr/src/lib/iam-utils/node_modules/request-promise/node_modules/request-promise-core/lib/errors.js:32:15)\n    at Request.plumbing.callback (/usr/src/lib/iam-utils/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:104:33)\n    at Request.RP$callback [as _callback] (/usr/src/lib/iam-utils/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at Request.self.callback (/usr/src/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:513:28)\n    at Request.<anonymous> (/usr/src/node_modules/request/request.js:1161:10)\n    at Request.emit (node:events:513:28)\n    at IncomingMessage.<anonymous> (/usr/src/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (node:events:627:28)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"},"msg":"Failed to get IAM token","time":

I'm able to resolve this issue once i generated component-orchestrator token with adding permission (iam.token.update).  but it's not available in OIH documentation (https://openintegrationhub.github.io/docs/3%20-%20GettingStarted/GCPInstallationGuide.html)

**Comment by RobinBrinkmann** [comment]
Could you please just add your solution to the docs and PR. Thanks @cggrafana12.
